title: CyberSecurity by psoutzis
description: Portfolio, blog, and projects related to cyber security; based in Cyprus.
url: "https://cyber-security.com.cy/"
baseurl: ""

author:
  name: Petros Soutzis
  email: psoutzis@cyber-security.com.cy

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-default-layout

search_enabled: true
heading_anchors: true
nav_enabled: true
color_scheme: nil
aux_links_new_tab: true
permalink: /blog/:title/

aux_links:
  GitHub:
    - "https://github.com/soutzis/"
  LinkedIn:
    - "https://www.linkedin.com/in/petrossoutzis/"
